export const STUDENT_ROUTES = {
  PAGES: {
    DASHBOARD: '/student',
    MY_CLASS: '/student/my-class',
    ATTENDANCE: '/student/attendance',
    EXAMS: '/student/exams',
    RESULTS: '/student/results',
    ASSIGNMENTS: '/student/assignments',
    ONLINE_CLASSES: '/student/online-classes',
    ONLINE_EXAMS: '/student/online-exams',
    STUDY_MATERIAL: '/student/study-material',
    PREVIOUS_PAPERS: '/student/previous-papers',
    SYLLABUS: '/student/syllabus',
    TIMETABLE: '/student/timetable',
    DOUBTS: '/student/doubts',
    LEAVE: '/student/leave',
    FEE: '/student/fee',
    REPORT_CARD: '/student/report-card',
    NOTICES: '/student/notices',
    NOTIFICATIONS: '/student/notifications',
    MESSAGING: '/student/messaging',
    CERTIFICATES: '/student/certificates',
    FEEDBACK: '/student/feedback',
    AI_NOTES: '/student/ai-notes',
    AI_SETTINGS: '/student/ai-settings',
    PROFILE: '/student/profile',
  },
  API: {
    CLASS_INFO: '/api/v1/student/class-info',
    RESULTS: '/api/v1/student/results',
    AI_GENERATE: '/api/v1/ai/generate',
    NOTICES: '/api/v1/resources/notices',
    ONLINE_CLASSES: '/api/v1/resources/online-classes',
    UPLOAD: '/api/v1/upload',
  }
} as const;
